name: Generate Index Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Allow pushing commits to the repository
      workflows: write  # Allow updates to workflow files, if necessary

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Step 3: Install dependencies
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip

      # Step 4: Generate index.md files
      - name: Generate index.md files
        run: |
          python generate_index.py

      # Step 5: Commit and push changes
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto-generate index.md files" || echo "No changes to commit"
          git push